version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run:
          name: Check Go version
          command: go version
      - run:
          # related to: https://github.com/golang/go/issues/31997
          name: Set GO111MODULE
          command: go env -w GO111MODULE=auto
      - run:
          name: Compile for Mac
          command: |
            GOOS=darwin GOARCH=amd64 go build -o Chapter_1-mac
      - run:
          name: Complie for Windows
          command: GOOS=windows GOARCH=amd64 go build -o Chapter_1-windows.exe
      - run:
          name: Complie for Linux
          command: GOOS=linux GOARCH=amd64 go build -o Chapter_1-linux
      - run:
          name: List all artifacts(bins)
          command: ls -l

workflows:
  compile-all-os:
    jobs:
      - build
