version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run:
          name: Check Go version
          command: go version
      - run:
          name: Compile for Mac
          command: | 
          pwd
          ls -l
          GOOS=darwin GOARCH=amd64 go build -o Chapter_1-mac
      - run:
          name: Complie for Windows
          command: GOOS=windows GOARCH=amd64 go build -o Chapter_1-windows.exe
      - run:
          name: Complie for Linux
          command: GOOS=linux GOARCH=amd64 go build -o Chapter_1-windows.exe
      - run:
          name: List all bins
          command: ls -l

workflows:
  compile-all-os:
    jobs:
      - build
